import { Stub } from '../components/primitives/index.js'
export default function Entities() {
  return (
    <Stub
      eyebrow="Structure" tone="secondary" sprint={1}
      title="Entities"
      lede="Every label, publisher, distributor, PRO, DSP, promoter, catalog fund, PE sponsor, debt investor, and rights database — one flat table."
      lands={[
        'src/data/entities.js — type (primary facet) + roles[] for multi-role companies (Sony, Concord, Downtown, SESAC)',
        'Filterable, searchable list with type · tier · parent · HQ facets',
        'Entity detail page: profile, parent chain, related deals, per-entity autogenerated fallback (typed defaults, never null)',
        'Every record carries asOf + sources[]',
      ]}
      related={[['/flows', 'Flows'], ['/deals', 'Deals']]}
    />
  )
}
