/**
 * categoryDeck.js — buildCategoryDeck(categoryId) → doc. A sector deck for one PEPI client category:
 * Thesis · Market context (by lens) · Who · Deals · Hypotheses by line · KPIs · Watch · Sources.
 */
import { getCategory, SERVICE_LINES, SERVICE_ORDER } from '../data/consulting.js'
import { ENTITY_TYPES, TIERS, OWNERSHIP } from '../data/entities.js'
import { TX_TYPES, ABS_MARKET, TX_TOTALS } from '../data/transactions.js'
import { GLOBAL_COLLECTIONS } from '../data/pros.js'
import { MARKET } from '../data/fundamentals.js'
import { formatMoney, formatPct, formatCount, formatDate } from './format.js'

const TOPIC_LABELS = { 'catalog-deal': 'Catalog deal', abs: 'ABS / credit', 'pe-capital': 'PE / capital', 'm&a': 'M&A', 'dsp-economics': 'DSP economics', 'pro-reform': 'PRO / licensing', litigation: 'Litigation', ai: 'AI', live: 'Live / ticketing', earnings: 'Earnings', policy: 'Policy' }

export function buildCategoryDeck(categoryId) {
  const c = getCategory(categoryId)
  if (!c) return null
  const sections = []
  const add = (eyebrow, title, blocks) => { const b = blocks.filter(Boolean); if (b.length) sections.push({ eyebrow, title, blocks: b }) }
  const sources = []

  add('Thesis', c.label, [{ kind: 'paragraph', text: c.description }, { kind: 'paragraph', text: c.thesis }, { kind: 'bullets', items: c.triggers.map((t) => `Trigger: ${t}`) }])

  const ctx = []
  if (c.lens === 'money') {
    ctx.push({ kind: 'stats', items: [{ label: 'Music ABS rated since 2020 (KBRA)', value: formatMoney(ABS_MARKET.ratedSince2020) }, { label: 'Issuance 2025', value: formatMoney(ABS_MARKET.issuance2025) }, { label: 'KBRA forecast 2026', value: formatMoney(ABS_MARKET.forecast2026) }, { label: 'Deals on file (all)', value: formatMoney(TX_TOTALS.disclosed) }] }, { kind: 'paragraph', text: ABS_MARKET.note })
    sources.push(ABS_MARKET.source)
  }
  if (c.lens === 'publishing') {
    ctx.push({ kind: 'stats', items: [{ label: `CISAC music collections ${GLOBAL_COLLECTIONS.year}`, value: formatMoney(GLOBAL_COLLECTIONS.music, { currency: '€' }) }, { label: 'Growth', value: formatPct(GLOBAL_COLLECTIONS.musicGrowth) }, { label: 'Digital share', value: formatPct(GLOBAL_COLLECTIONS.digitalShare) }] }, { kind: 'paragraph', text: GLOBAL_COLLECTIONS.note })
    sources.push(GLOBAL_COLLECTIONS.source)
  }
  if (c.lens === 'recording' || c.lens === 'structure') {
    ctx.push({ kind: 'stats', items: [{ label: `Recorded music ${MARKET.ifpi.year} (IFPI)`, value: formatMoney(MARKET.ifpi.recordedRevenue) }, { label: 'Streaming share', value: formatPct(MARKET.ifpi.streamingShare) }, { label: 'Paid subscribers (MIDiA)', value: formatCount(MARKET.midia.subscribers) }] }, { kind: 'paragraph', text: MARKET.ifpi.note })
    sources.push(MARKET.ifpi.source, MARKET.midia.source)
  }
  add('Market', 'Context', ctx)

  add('Who', `${c.members.length} entities in scope`, [
    { kind: 'table', columns: ['Entity', 'Type', 'Tier', 'Ownership', 'HQ'], rows: c.members.slice(0, 30).map((e) => [e.name, ENTITY_TYPES[e.type]?.label || e.type, TIERS[e.tier]?.split(' ·')[0] || String(e.tier), OWNERSHIP[e.ownership] || e.ownership, e.hq || '—']) },
    c.members.length > 30 ? { kind: 'note', text: `${c.members.length - 30} more in the app.` } : null,
  ])
  add('Money', 'Transactions touching the category', [
    { kind: 'stats', items: [{ label: 'Deals on file', value: String(c.deals.length) }, { label: 'Disclosed volume', value: formatMoney(c.dealVolume) }] },
    { kind: 'table', columns: ['Date', 'Deal', 'Type', 'Value'], rows: c.deals.slice(0, 14).map((t) => [formatDate(t.date), t.title, TX_TYPES[t.type]?.label || t.type, t.value ? formatMoney(t.value, { digits: 2 }) : t.valueNote || '—']) },
  ])
  add('Engagements', 'Hypotheses by service line', SERVICE_ORDER.map((l) => ({ kind: 'bullets', items: (c.engagements[l] || []).map((h) => `${SERVICE_LINES[l].label}: ${h}`) })))
  add('Metrics', 'KPIs a deal team asks for', [{ kind: 'bullets', items: c.kpis }])
  add('Watch', 'Signals to monitor', [{ kind: 'bullets', items: c.topics.map((t) => TOPIC_LABELS[t] || t) }])
  add('Sources', 'Provenance', [{ kind: 'bullets', items: sources.map((s) => `${s.label} — ${s.url}`) }, { kind: 'note', text: 'Entity-level sources are on each entity page. Generated by Mainframe · Music.' }])

  sections.forEach((s, i) => { s.num = i + 1 })
  return { kind: 'category-deck', category: c, entity: null, mode: 'category-deck', modeLabel: 'Sector deck', title: c.label, subtitle: `A&M PEPI client category · ${c.lens}`, slug: `${c.id}-sector-deck`, generatedAt: new Date().toISOString(), asOf: '2026-09-14', sections, citations: { items: [], source: 'empty' } }
}
