#!/usr/bin/env node
/**
 * export-edition.mjs — writes a standalone source tree of the research edition.
 *
 *   npm run edition:work -- --out ../music-mainframe-work
 *
 * The build-time swap protects the BUNDLE. This protects the REPOSITORY: if the firm wants to host the work
 * edition itself, or review its code, handing over this repo would hand over the authored material in its
 * history as well. So the export copies an allowlist, deletes the private sources outright, materialises the
 * stubs in their place, rewrites the manifest and README, and then greps every copied file for strings that
 * exist only in the private modules. A leak is a failure, not a warning: the tree is deleted.
 *
 * Flags: --out <dir> (required) · --force (overwrite a tree this script made) · --no-build (skip the build check)
 */
import { execFileSync } from 'node:child_process'
import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'
import { WORK_SWAPS } from '../vite.config.js'
import { EDITIONS, FRAMING } from '../src/editions.js'
import { CLIENT_CATEGORIES } from '../src/data/consulting.js'
import { ROLES } from '../src/data/rateCard.js'
import { PERSONAS } from '../src/data/personas.js'
import { HOOKS } from '../src/data/playbooks.js'
import { CASE_LIST } from '../src/data/cases/index.js'
import { HUB_URL } from '../src/data/siblings.js'

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..')
const args = process.argv.slice(2)
const arg = (name, fallback) => { const i = args.indexOf(`--${name}`); return i >= 0 && args[i + 1] ? args[i + 1] : fallback }
const OUT = arg('out', '')
const FORCE = args.includes('--force')
const BUILD = !args.includes('--no-build')
const MARKER = '.mm-edition-export'
if (!OUT) { console.error('usage: npm run edition:work -- --out ../music-mainframe-work [--force] [--no-build]'); process.exit(1) }
const out = path.resolve(root, OUT)
const die = (msg) => { console.error(`\nFAIL ${msg}`); process.exit(1) }

/** Copied wholesale. An allowlist, not a denylist: a new private directory must be added here to escape. */
const COPY = ['index.html', 'vite.config.js', 'eslint.config.js', 'package.json', 'package-lock.json', 'public', 'src', 'server']
/** Scripts the research edition can actually run. The lab and overlay suites import material it does not have. */
const SCRIPTS = ['build-tokens.mjs', 'check-health.mjs', 'watch-server.mjs', 'generate-briefs.mjs', 'test-contrast.mjs', 'test-glossary.mjs', 'test-market.mjs', 'test-outcomes.mjs', 'test-prospect.mjs', 'test-xlsx.mjs']
/**
 * Deleted from the copy. The swapped modules are here too: a swap keeps content out of the bundle, but the
 * file itself would still be sitting in the exported tree for anyone to open.
 */
const PRIVATE_SOURCES = [
  ...WORK_SWAPS.map(([from]) => from),
  'src/data/cases',
  'src/components/lab',
  'src/hooks/useLabState.js',
  'src/utils/pmi.js', 'src/utils/abs.js', 'src/utils/carveout.js',
  'src/utils/pmiState.js', 'src/utils/absState.js', 'src/utils/carveState.js', 'src/utils/labState.js',
  'src/utils/pmiDocs.js', 'src/utils/absDocs.js', 'src/utils/carveDocs.js', 'src/utils/labEngines.js',
]

// ── the tree ────────────────────────────────────────────────────────────────────────────────────────────
if (fs.existsSync(out)) {
  if (!FORCE) die(`${out} already exists. Re-run with --force to replace a tree this script made, or remove it yourself.`)
  if (!fs.existsSync(path.join(out, MARKER))) die(`${out} exists but was not made by this script (no ${MARKER}). Refusing to delete someone else's directory.`)
  fs.rmSync(out, { recursive: true, force: true })
}
fs.mkdirSync(out, { recursive: true })
fs.writeFileSync(path.join(out, MARKER), `generated by scripts/export-edition.mjs on ${new Date().toISOString()}\n`)

for (const rel of COPY) {
  const from = path.join(root, rel)
  if (!fs.existsSync(from)) die(`missing source: ${rel}`)
  fs.cpSync(from, path.join(out, rel), { recursive: true })
}
fs.mkdirSync(path.join(out, 'scripts'), { recursive: true })
for (const s of SCRIPTS) fs.cpSync(path.join(root, 'scripts', s), path.join(out, 'scripts', s))

let removed = 0
for (const rel of new Set(PRIVATE_SOURCES)) {
  const p = path.join(out, rel)
  if (fs.existsSync(p)) { fs.rmSync(p, { recursive: true, force: true }); removed++ }
}
// The stubs take the place of what they replaced, so every importer still resolves and the build-time swap
// (still configured in vite.config.js) becomes a no-op rather than a dangling path.
for (const [from, to] of WORK_SWAPS) {
  fs.mkdirSync(path.dirname(path.join(out, from)), { recursive: true })
  fs.copyFileSync(path.join(root, to), path.join(out, from))
}

// ── the manifest and the README ─────────────────────────────────────────────────────────────────────────
const pkg = JSON.parse(fs.readFileSync(path.join(root, 'package.json'), 'utf8'))
const keepScript = (k) => !['test:valuation', 'test:pmi', 'test:abs', 'test:carveout', 'test:edition', 'test:work', 'test', 'build', 'build:work', 'dev', 'start', 'server'].includes(k)
pkg.name = 'music-mainframe-work'
pkg.description = FRAMING.title
pkg.scripts = {
  ...Object.fromEntries(Object.entries(pkg.scripts).filter(([k]) => keepScript(k))),
  dev: 'MM_EDITION=work vite',
  build: 'MM_EDITION=work vite build',
  server: 'MM_EDITION=work node server/index.js',
  start: 'MM_EDITION=work node server/index.js',
  test: 'npm run test:contrast && npm run test:glossary && npm run test:market && npm run test:outcomes && npm run test:prospect && npm run test:xlsx',
}
fs.writeFileSync(path.join(out, 'package.json'), `${JSON.stringify(pkg, null, 2)}\n`)

fs.writeFileSync(path.join(out, 'README.md'), `# ${FRAMING.title}

${FRAMING.what}

${FRAMING.notProduct} ${FRAMING.sources}

${FRAMING.data}

## Running it

\`\`\`bash
npm ci --include=dev
npm run build      # writes dist-work/
npm start          # serves the build and the news aggregator on :3002
npm test           # the engines and the documents they produce
\`\`\`

## What is in here

Sections: ${EDITIONS.work.groups.join(' · ')}. Exports: ${EDITIONS.work.exports.join(' · ')}.

Every record carries \`asOf\` and \`sources[]\`. Scores are computed by the engines in \`src/utils/\` from those
records and show their reasoning on screen; none is typed in by hand. Anything an operator types — status,
notes, outcomes — stays in their own browser and is never uploaded.

## Environment

| Variable | Effect |
| --- | --- |
| \`MM_EDITION=work\` | Serves \`dist-work\`. Set by every script here. |
| \`EMBED_ALLOW\` | Hosts permitted to frame the app (a SharePoint tenant, say). Unset refuses all framing. |
| \`ACCESS_USER\` / \`ACCESS_PASS\` | Put the site behind basic auth. \`/api/health\` stays open so uptime checks keep working. |
| \`SEC_USER_AGENT\` | \`Name email\` — SEC EDGAR requires a declared contact and rate-limits hard. Without it, filings coverage falls back to seeded identifiers and the app says so. |

Generated from the full repository by \`scripts/export-edition.mjs\`. Edit there, not here.
`)

fs.writeFileSync(path.join(out, 'render.yaml'), `services:
  - type: web
    name: music-mainframe-work
    runtime: node
    region: oregon
    plan: free
    buildCommand: npm ci --include=dev && npm run build
    startCommand: npm start
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: MM_EDITION
        value: work
      - key: EMBED_ALLOW
        sync: false
      - key: ACCESS_USER
        sync: false
      - key: ACCESS_PASS
        sync: false
      - key: SEC_USER_AGENT
        sync: false
`)
fs.writeFileSync(path.join(out, '.gitignore'), 'node_modules\ndist\ndist-work\nexports\n.env\n.env.*\n.DS_Store\n')

// ── the check that makes the export worth trusting ──────────────────────────────────────────────────────
const files = []
const walk = (dir) => { for (const e of fs.readdirSync(dir, { withFileTypes: true })) { const p = path.join(dir, e.name); if (e.name === 'node_modules') continue; if (e.isDirectory()) walk(p); else files.push(p) } }
walk(out)
const readable = files.filter((f) => /\.(js|jsx|mjs|json|css|html|md|yaml|txt)$/.test(f))

const samples = [
  ...CLIENT_CATEGORIES.map((c) => ['category thesis', c.thesis.slice(0, 60)]),
  ...CLIENT_CATEGORIES.flatMap((c) => Object.values(c.engagements || {}).flat().map((h) => ['engagement hypothesis', h.slice(0, 50)])),
  ...ROLES.map((r) => ['rate-card role', r.label]),
  ...PERSONAS.map((p) => ['persona question', p.question.slice(0, 40)]),
  ...HOOKS.map((h) => ['outreach hook', h.claim.slice(0, 50)]),
  ...CASE_LIST.flatMap((c) => [['lab case title', c.title], ['lab case client', c.client.name]]),
  ['internal cross-link', HUB_URL],
  ['internal application', 'am-intelligence-hub'],
  ['practice label', 'PEPI'],
]
const leaks = []
for (const f of readable) {
  const text = fs.readFileSync(f, 'utf8')
  for (const [label, s] of samples) if (s && text.includes(s)) leaks.push(`${path.relative(out, f)} — ${label}: "${s.slice(0, 48)}"`)
}
if (leaks.length) {
  fs.rmSync(out, { recursive: true, force: true })
  console.error(`\n${leaks.length} private string(s) reached the export — tree deleted:`)
  for (const l of leaks.slice(0, 20)) console.error(`  ${l}`)
  process.exit(1)
}

if (BUILD) {
  // Proving it builds matters more than proving it copies: deleting one file too many is the likely mistake.
  // The source repo's node_modules is borrowed rather than installed, so this costs seconds, not minutes.
  const link = path.join(out, 'node_modules')
  if (!fs.existsSync(link)) fs.symlinkSync(path.join(root, 'node_modules'), link, 'dir')
  try {
    execFileSync('npx', ['vite', 'build'], { cwd: out, env: { ...process.env, MM_EDITION: 'work' }, stdio: 'pipe' })
  } catch (err) {
    die(`the exported tree does not build — a file was removed that something still imports.\n${String(err.stderr || err.message).slice(0, 1200)}`)
  } finally {
    fs.rmSync(link, { force: true })
    fs.rmSync(path.join(out, 'dist-work'), { recursive: true, force: true })
  }
}

const kb = (files.reduce((a, f) => a + fs.statSync(f).size, 0) / 1024).toFixed(0)
console.log(`\n${path.relative(root, out) || out} — ${files.length} files, ${kb} KB`)
console.log(`removed ${removed} private paths · materialised ${WORK_SWAPS.length} stubs · scanned ${readable.length} files against ${samples.length} private strings · ${BUILD ? 'builds clean' : 'build skipped'}`)
console.log(`next: cd ${OUT} && git init && npm ci --include=dev && npm run build && npm start`)
